name: Test building jupyter-book
# Controls when the action will run.
on:
  push:
    branches: ["**"]


env:
  # Directory that will be published on github pages
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  matrix:
        backend: ["panel", "trame"]

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    env:
      PYVISTA_OFF_SCREEN: false
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
      PYVISTA_TRAME_SERVER_PROXY_PREFIX: '/proxy/'
      PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"

    steps:
      - uses: actions/checkout@v3

      - name: Install apt dependencies and upgrade pip
        run: |
          apt-get update && apt-get install -y python3-pip git libgl1-mesa-glx libxrender1 xvfb

      - name: Install python requirements
        run: |
          python3 -m pip --no-cache-dir install -r requirements.txt --upgrade

      - name: Build the book
        run: 
          PYVISTA_JUPYTER_BACKEND=${{ matrix.backend }} jupyter-book build .

      - name: Upload book
        uses: actions/upload-artifact@v3
        with:
          name: book${{ matrix.backend }}
          path: _build/html
